config/routes.rb
Rails.application.routes.draw do
  devise_for :admins#, skip: [:registrations]
  root 'welcome#index'

  get 'index' => 'welcome#index'

  resources :posts

  post 'preview' => 'preview#show', as: :preview
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :preview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  # TODO FIX ME OKAY
  #before_action :authenticate_admin!, except: [:index, :show]

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :preview, :content, :author)
    end
end

app/controllers/preview_controller.rb
class PreviewController < ApplicationController
  def show
    render layout: false
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  class HTMLwithPygments < Redcarpet::Render::HTML
    include Redcarpet::Render::SmartyPants

    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end

  def markdown(text)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: false)
    options = {
      filter_html: false,
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true,
      tables: true,
      footnotes: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text.to_s).html_safe
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TeamRocketWebsite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id="page-top" class="index">

<% if !current_page?('/') && !current_page?('/index') %>

<% end %>

<%= yield %>

<%= javascript_include_tag 'application'%>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :preview %><br>
    <%= f.text_area :preview %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<div id="live-preview" data-preview-url="<%= preview_path %>"></div>

app/views/posts/_navbar.html.erb
<nav class="navbar navbar-default navbar-custom navbar-fixed-top affix">
  <div class="container">
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        Menu <i class="fa fa-bars" aria-hidden="true"></i>
      </button>

      <a class="navbar-brand page-scroll" href="#page-top">Team Rocket VUW</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path, { class: 'page-scroll' } %></li>
        <li><%= link_to 'Blog', '/posts', { class: 'page-scroll' } %></li>
        <% if admin_signed_in? %>
          <li><%= link_to 'new blog post', new_post_path, { class: 'page-scroll' } %></li>
          <li><%= link_to('Logout', destroy_admin_session_path, :method => :delete) %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= render 'navbar' %>

<div class="container" id="blog-div">
  <div class="row">
    <% @posts.each do |post| %>
      <div class="col col-lg-4 col-md-6 col-sm-12">
        <div class="post vertically-centered">
          <h3 class="post-title text-center"><%= post.title %></h3>
          <p class="post-author text-center"><%= post.author.capitalize %> on <%= post.created_at.strftime("%B %d, %Y") %></p>

          <p class="post-preview text-center"><%= post.preview %></p>

          <div class="centered">
            <button type="button" class="btn btn-default"><%= link_to "Read More", post_path(post) %></button>
          </div>

          <% if admin_signed_in? %>
          <div class="centered admin-controls">
            <p><%= link_to "Edit Post", edit_post_path(post) %></p>
            <p><%= link_to "Delete Post", post_path(post), method: :delete, data: { confirm: "Are you sure?" } %></p>
          </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%= render 'navbar' %>

<div class="container" id="blog-div">
  <p>
    <strong>Title:</strong>
    <%= @post.title %>
  </p>

  <div class="post-body">
    <%= markdown(@post.content) %>
  </div>

  <p>
    <strong>Author:</strong>
    <%= @post.author %>
  </p>

  <%= link_to 'Edit', edit_post_path(@post) %> |
  <%= link_to 'Back', posts_path %>

</div>

app/views/preview/show.html.erb
<%= markdown(params[:text]) %>

app/views/welcome/_footer.html.erb
<footer class="bg-white">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <span class="copyright">Copyright &copy; Team Rocket VUW 2016</span>
      </div>
      <div class="col-md-4">
        <ul class="list-inline social-buttons">
          <li><a href="https://www.youtube.com/channel/UC0N7pZTfCQ7TR1frvrsH7Lw"><i class="fa fa-youtube"></i></a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/welcome/_goals_section.html.erb
<section id="goals" class="bg-white">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">Project Goals</h2>
        <h3 class="section-subheading text-muted">Project Goals For 2016</h3>
      </div>
    </div>
    <div class="row text-center">
      <div class="col-md-4">
        <span class="fa-stack fa-4x">
          <i class="fa fa-circle fa-stack-2x text-primary"></i>
          <i class="fa fa-rocket fa-stack-1x fa-inverse"></i>
        </span>
        <h4 class="goal-heading">Launch K-Motor</h4>
        <p class="text-muted">The final goal of the project is to launch an actively stabilised rocket using the class K motor. We are building to this launch by first launching a passively stabilised class D motor to gain telemetry data.</p>
      </div>
      <div class="col-md-4">
        <span class="fa-stack fa-4x">
          <i class="fa fa-circle fa-stack-2x text-primary"></i>
          <i class="fa fa-wrench fa-stack-1x fa-inverse"></i>
        </span>
        <h4 class="goal-heading">Design Modular Hardware</h4>
        <p class="text-muted">As the Team Rocket project is likely to be carrie on by future teams, we aim to created highly modular hardware components. Allowing for our work to be reused by future avionics teams.</p>
      </div>
      <div class="col-md-4">
        <span class="fa-stack fa-4x">
          <i class="fa fa-circle fa-stack-2x text-primary"></i>
          <i class="fa fa-code fa-stack-1x fa-inverse"></i>
        </span>
        <h4 class="goal-heading">Open Source</h4>
        <p class="text-muted">All components of the system, including hardware, software and collected data will be freely available through open source. As such, we must ensure a high standard of quality for our work.</p>
      </div>
    </div>
  </div>
</section>

app/views/welcome/_header.html.erb
<header>
  <div class="container">
    <div class="intro-text">
      <div class="intro-lead-in">ENGR302 Rocket Avionics Project</div>
      <div class="intro-heading">Blasting off in 2016</div>
      <a href="#goals" class="page-scroll btn btn-xl smooth-scroll">Find Out More</a>
    </div>
  </div>
</header>

app/views/welcome/_navbar.html.erb
<nav id="mainNav" class="navbar navbar-default navbar-custom navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          Menu <i class="fa fa-bars" aria-hidden="true"></i>
      </button>

      <%= render 'navbar_brand' %>
    </div>

    <%= render 'navbar_links' %>
  </div>
</nav>

app/views/welcome/_navbar_brand.html.erb
<a class="navbar-brand page-scroll" href="#page-top">Team Rocket VUW</a>

app/views/welcome/_navbar_links.html.erb
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  <ul class="nav navbar-nav navbar-right">
    <li class="hidden"><a href="#page-top"></a></li>
    <li><%= link_to 'Goals', { anchor: 'goals' } , { class: 'page-scroll smooth-scroll' } %></li>
    <li><%= link_to 'Timeline', { anchor: 'timeline' } , { class: 'page-scroll  smooth-scroll' } %></li>
    <li><%= link_to 'Team', { anchor: 'team' }, { class: 'page-scroll smooth-scroll' } %></li>
    <%#<li><%= link_to 'Blog', posts_path, { class: 'page-scroll' } </li>%>
  </ul>
</div>

app/views/welcome/_sponsors.html.erb
<aside class="clients bg-light-gray">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h3 class="section-subheading">Proudly Sponsored By</h3>
      </div>

      <div class="col-md-6 col-md-offset-3 col-sm-12">
        <a href="http://www.victoria.ac.nz/">
          <%= image_tag 'vic', class: 'img-responsive img-centered' %>
        </a>
      </div>
    </div>
  </div>
</aside>

app/views/welcome/_team.html.erb
<section id="team" class="bg-white">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">Team Rocket</h2>
        <h3 class="section-subheading text-muted">None of us is as smart as all of us.</h3>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-4">
        <div class="team-member">
          <%= image_tag 'chelsea', class: 'img-responsive img-circle' %>
          <h4>Chelsea Miller</h4>
          <p class="text-muted">Elections and Computer Systems Engineer</p>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="team-member">
          <%= image_tag 'tre', class: 'img-responsive img-circle' %>
          <h4>Tré Kani</h4>
          <p class="text-muted">Elections and Computer Systems Engineer</p>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="team-member">
          <%= image_tag 'harrison', class: 'img-responsive img-circle' %>
          <h4>Harrison Jones</h4>
          <p class="text-muted">Elections and Computer Systems Engineer</p>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="team-member">
          <%= image_tag 'jamie', class: 'img-responsive img-circle' %>
          <h4>Jamie Sanson</h4>
          <p class="text-muted">Elections and Computer Systems Engineer</p>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="team-member">
          <%= image_tag 'lauren', class: 'img-responsive img-circle' %>
          <h4>Lauren Hucker</h4>
          <p class="text-muted">Software Engineer</p>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="team-member">
          <%= image_tag 'marcel', class: 'img-responsive img-circle' %>
          <h4>Marcel van Workum</h4>
          <p class="text-muted">Software Engineer</p>
        </div>
      </div>
    </div>
    <div class="row" style="padding-top: 40px;">
      <div class="col-lg-12">
        <div class="col-sm-6">
          <div class="team-member">
            <%= image_tag 'andre', class: 'img-responsive img-circle' %>
            <h4>Andre Geldenhuis</h4>
            <p class="text-muted">Project Client</p>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="team-member">
            <%= image_tag 'holly', class: 'img-responsive img-circle' %>
            <h4>Holly Ade-Simpson</h4>
            <p class="text-muted">Project Champion</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/welcome/_timeline.html.erb
<section id="timeline" class="bg-light-gray">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">Project Timeline</h2>
        <h3 class="section-subheading text-muted">Team Rocket's Timeline For 2016</h3>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <ul class="timeline">
          <li>
            <div class="timeline-image">
              <%= image_tag 'paper', class: 'img-circle img-responsive' %>
            </div>
            <div class="timeline-panel">
              <div class="timeline-heading">
                <h4>March - May</h4>
                <h4 class="subheading">Preliminary Reasearch</h4>
              </div>
              <div class="timeline-body">
                <p class="text-muted">During the initial phase of the project, we completed an extensive amount of research. This allowed us to know exactly what we needed to build and how we were going to go about buildining it.</p>
              </div>
            </div>
          </li>
          <li class="timeline-inverted">
            <div class="timeline-image">
              <%= image_tag 'management', class: 'img-circle img-responsive' %>
            </div>
            <div class="timeline-panel">
              <div class="timeline-heading">
                <h4>May - June</h4>
                <h4 class="subheading">Project Management + H&S</h4>
              </div>
              <div class="timeline-body">
                <p class="text-muted">At this stage, we spent a lot of time creating a rigorous set of project management documentenation, as well as an extensive health and safety plan.</p>
              </div>
            </div>
          </li>
          <li>
            <div class="timeline-image">
              <%= image_tag 'launch', class: 'img-circle img-responsive' %>
            </div>
            <div class="timeline-panel">
              <div class="timeline-heading">
                <h4>July</h4>
                <h4 class="subheading">Initial Launch</h4>
              </div>
              <div class="timeline-body">
                <p class="text-muted">Team Rocket hopes to launch a class D motor, using a passively stabilised rocket. This will allow for the collection of sample telemetry data, which will be vital moving forward in the project.</p>
              </div>
            </div>
          </li>
          <li class="timeline-inverted">
            <div class="timeline-image">
              <%= image_tag 'phase2', class: 'img-circle img-responsive' %>
            </div>
            <div class="timeline-panel">
              <div class="timeline-heading">
                <h4>July - September</h4>
                <h4 class="subheading">Phase Two</h4>
              </div>
              <div class="timeline-body">
                <p class="text-muted">After the initial launch, work will begin on developing a much larger, and actively stabilised rocket capable of launching a class K motor. </p>
              </div>
            </div>
          </li>
          <li class="timeline-inverted">
            <div class="timeline-image">
              <h4>Watch
                <br>This
                <br>Space !</h4>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </section>

app/views/welcome/index.html.erb
<%= render 'navbar' %>
<%= render 'header' %>
<%= render 'goals_section' %>
<%= render 'timeline' %>
<%= render 'team' %>
<%= render 'sponsors' %>
<%= render 'footer' %>